[package]
name = "rqlite-rs-axum-problem"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
rqlite-rs = "0.6.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
